version: '3.8'
services:
  factory-experience-backend-replica-1:
    container_name: factory-experience-backend-replica-1
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=hard-to-guess
      - JWT_EXPIRATION=604800
      - LOG_LEVELS=error,warn,debug,log
      - LOGGING_CONTEXT=factory-experience-backend-replica-1
    networks:
      - backend_network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres

  factory-experience-backend-replica-2:
    container_name: factory-experience-backend-replica-2
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=hard-to-guess
      - JWT_EXPIRATION=604800
      - LOG_LEVELS=error,warn,debug,log
      - LOGGING_CONTEXT=factory-experience-backend-replica-2
    networks:
      - backend_network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - factory-experience-backend-replica-1
      - factory-experience-backend-replica-2
    networks:
      - backend_network

  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend_network
    ports:
      - '5050:80'
    depends_on:
      - postgres

  factory-experience-frontend:
    container_name: factory-experience-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - backend_network
    ports:
      - "8080:8080"
    depends_on:
      - nginx

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: { }
